language: bash
services: docker
branches:
  only:
    - master
    - deploy
    - feature/jfc/mastarm-deployment
cache:
  yarn: true
notifications:
  email: false
env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH
before_install:
  - pip install --user awscli==1.16.*
scripts:
  - ./scripts/test
deploy:
  provider: script
  skip_cleanup: true
  script: ENV=staging scripts/cipublish
  on:
    branch: feature/jfc/mastarm-deployment
deploy:
  provider: script
  skip_cleanup: true
  script: ENV=production scripts/cipublish
  on:
    branch: master
