language: bash
services: docker
branches:
  only:
    - master
    - develop
    - feature/jfc/mastarm-deployment
notifications:
  email: false
env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH
before_install:
  - pip install --user awscli==1.16.*
script:
  - ./scripts/test
deploy:
  - provider: script
    skip_cleanup: true
    script: ENV=staging ECHOLOCATOR_DEBUG=true scripts/cipublish
    on:
      repo: azavea/echo-locator
      branch: feature/jfc/mastarm-deployment
  - provider: script
    skip_cleanup: true
    script: ENV=production scripts/cipublish
    on:
      repo: azavea/echo-locator
      branch: master
