version: '3'
services:
  taui:
    build: ./taui
    volumes:
      - ./taui:/usr/local/src
      - $HOME/.aws:/root/.aws:ro
    working_dir: /usr/local/src
    ports:
      - "9966:9966"
    entrypoint: yarn
    command: start
