version: '3'
services:
  terraform:
    image: quay.io/azavea/terraform:0.11.11
    volumes:
      - ./:/usr/local/src
      - $HOME/.aws:/root/.aws:ro
    environment:
      - AWS_PROFILE=echo-locator
      - GIT_COMMIT=${GIT_COMMIT:-latest}
      - ECHOLOCATOR_DEBUG=1
      - ECHOLOCATOR_SETTINGS_BUCKET=${ECHOLOCATOR_SETTINGS_BUCKET:-echo-locator-staging-config-us-east-1}
      - ECHOLOCATOR_SITE_BUCKET=${ECHOLOCATOR_SITE_BUCKET:-echo-locator-staging-site-us-east-1}
    working_dir: /usr/local/src
    entrypoint: bash
