cloudfront: EJKZ46R7IC1BB
entries:
  - src/index.js:assets/index.js
  - src/index.css:assets/index.css
  - src/BHAlogo.png:assets/BHAlogo.png
  - config.json:assets/config.json
  - neighborhoods.json:assets/neighborhoods.json
  - neighborhood_bounds.json:assets/neighborhood_bounds.json
env: development
flyle: true
s3bucket: taui
